### ISSUE TITLE
community包中没有modurity属性

### ISSUE THREAD

**Issue by alkjoj** [QinY-Stat/CommunityDetection#7]
运行GN算法的时候，出现如下报错
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/fanjunlei/PycharmProjects/CommunityDetection/demo_GN.py", line 12, in <module>
    gn_com = GN.partition(G_copy)
  File "/Users/fanjunlei/PycharmProjects/CommunityDetection/algorithm/GN.py", line 35, in partition
    modularities = [cm.modularity(results[i], G_copy) for i in range(len(results))]
  File "/Users/fanjunlei/PycharmProjects/CommunityDetection/algorithm/GN.py", line 35, in <listcomp>
    modularities = [cm.modularity(results[i], G_copy) for i in range(len(results))]
AttributeError: module 'community' has no attribute 'modularity'`

尝试换用networkx.algorithm.community还是不行

**Comment by QianpengLi577** [comment]
pip install python-louvain  然后再运行就行，你试一试

**Comment by qinyuenlp** [comment]
community是使用pip install python-louvain安装的,请确认
